#!/usr/bin/env python3
"""
Regenerate coupons-manifest.js by reading Discount.xlsx.

Run this after editing Discount.xlsx:
    ./update-coupons.py

The .xlsx must have two columns:
    Discount_Coupon       Discount_Percentage
    50OFF                 0.5
    20OFF                 0.2
    ...

The first row is treated as a header.
Coupon codes are uppercased; percentages must be numbers (0.0 to 1.0).
"""
import json
import os
import sys
import xml.etree.ElementTree as ET
import zipfile

NS = {"main": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}

script_dir = os.path.dirname(os.path.abspath(__file__))
os.chdir(script_dir)

XLSX = "Discount.xlsx"
OUT = "coupons-manifest.js"


def read_xlsx(path):
    if not os.path.exists(path):
        return {}
    coupons = {}
    with zipfile.ZipFile(path) as z:
        # Shared strings (Excel stores strings in a separate table)
        strings = []
        try:
            with z.open("xl/sharedStrings.xml") as f:
                tree = ET.parse(f)
                for si in tree.getroot().findall("main:si", NS):
                    t = si.find(".//main:t", NS)
                    strings.append(t.text if (t is not None and t.text) else "")
        except KeyError:
            pass

        with z.open("xl/worksheets/sheet1.xml") as f:
            tree = ET.parse(f)
            rows = tree.getroot().findall(".//main:row", NS)
            header_seen = False
            for row in rows:
                cells = []
                for c in row.findall("main:c", NS):
                    typ = c.get("t")
                    v = c.find("main:v", NS)
                    val = v.text if v is not None else ""
                    if typ == "s" and val != "":
                        val = strings[int(val)]
                    cells.append(val)
                if not cells or not cells[0]:
                    continue
                if not header_seen:
                    header_seen = True
                    continue
                code = str(cells[0]).strip().upper()
                if not code or len(cells) < 2:
                    continue
                try:
                    pct = float(cells[1])
                except (ValueError, TypeError):
                    print(f"  ! Skipping {code}: '{cells[1]}' is not a number", file=sys.stderr)
                    continue
                if pct < 0 or pct > 1:
                    print(f"  ! Skipping {code}: percentage {pct} not in 0..1", file=sys.stderr)
                    continue
                coupons[code] = pct
    return coupons


def main():
    coupons = read_xlsx(XLSX)
    with open(OUT, "w") as f:
        f.write("// Auto-generated by update-coupons.py — do not edit by hand.\n")
        f.write(f"// Source: {XLSX}. Run ./update-coupons.py after editing.\n")
        f.write("window.COUPONS = " + json.dumps(coupons, indent=2) + ";\n")
    print(f"✓ Wrote {len(coupons)} coupon(s) to {OUT}")


if __name__ == "__main__":
    main()
