#!/bin/bash
# Regenerate catalog-manifest.js by scanning the catalog/ folder.
# Run this after adding or removing photos in catalog/.
#
# Usage:
#   ./update-catalog.sh
#
# Supports .jpg .jpeg .png .webp .gif (case-insensitive).
# Photos are sorted alphabetically by filename.

set -euo pipefail
cd "$(dirname "$0")"

OUT="catalog-manifest.js"

list_photos() {
  find catalog -maxdepth 1 -type f \
    \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" -o -iname "*.gif" \) \
    -exec basename {} \; | sort
}

count=0
if [ -d catalog ]; then
  count=$(list_photos | wc -l | tr -d ' ')
fi

{
  echo "// Auto-generated by update-catalog.sh — do not edit by hand."
  echo "// Run ./update-catalog.sh after changing files in catalog/."
  echo "window.CATALOG_PHOTOS = ["
  if [ -d catalog ]; then
    list_photos | sed 's/^/  "/; s/$/",/'
  fi
  echo "];"
} > "$OUT"

echo "✓ Wrote $count photo(s) to $OUT"
