#!/usr/bin/env python3
"""
Regenerate pics-manifest.js by scanning Windows_Pic/ and Macbook_Pic/
for image files named after Excel row numbers (e.g. 2.jpg, 15.png).

Output shape:

    window.PICS = {
      "windows": { "2": "jpg", "3": "png", ... },
      "macbook": { "2": "jpg", ... }
    };

The frontend consults window.PICS[platform][row] to decide whether to
render an <img> for a tile (and which extension to use). Rows not in
the manifest render the "No image" placeholder immediately, avoiding a
storm of 404s from the fallback-extension chain.

Run after adding or removing images:
    ./update-pics.py
"""
import json
import os
import re
import sys

script_dir = os.path.dirname(os.path.abspath(__file__))
os.chdir(script_dir)

FOLDERS = {"windows": "Windows_Pic", "macbook": "Macbook_Pic"}
EXTS_PRIORITY = ("jpg", "jpeg", "png", "webp")
OUT = "pics-manifest.js"


def scan(folder):
    out = {}
    if not os.path.isdir(folder):
        return out
    for fname in os.listdir(folder):
        m = re.match(r"^(\d+)\.([A-Za-z0-9]+)$", fname)
        if not m:
            continue
        row, ext = m.group(1), m.group(2).lower()
        if ext == "jpeg":
            ext = "jpg"
        if ext not in EXTS_PRIORITY:
            continue
        # If the row already has an entry, prefer the higher-priority extension.
        prev = out.get(row)
        if prev and EXTS_PRIORITY.index(prev) < EXTS_PRIORITY.index(ext):
            continue
        out[row] = ext
    return out


def main():
    data = {plat: scan(folder) for plat, folder in FOLDERS.items()}
    payload = json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by update-pics.py — do not edit by hand.\n")
        f.write("// Source: Windows_Pic/ and Macbook_Pic/. Run ./update-pics.py after\n")
        f.write("// adding or removing images.\n")
        f.write("window.PICS = " + payload + ";\n")
    total = sum(len(v) for v in data.values())
    print(f"✓ Wrote {total} image entries to {OUT} "
          f"(windows: {len(data['windows'])}, macbook: {len(data['macbook'])})")


if __name__ == "__main__":
    main()
